language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - nightly
  
sudo: false

matrix:
  allow_failures:
  - php: nightly

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

install:
  - phpize
  - EXTRA_LDFLAGS="-precious-files-regex .libs/php_stats.gcno" LDFLAGS="-lgcov" CFLAGS="-Wall -fno-strict-aliasing -coverage -O0" ./configure
  - make all

script:
  - TEST_PHP_EXECUTABLE=$(which php) php -n
    -d open_basedir= -d output_buffering=0 -d memory_limit=-1
    run-tests.php -n
    -d extension_dir=modules -d extension=stats.so --show-diff
    tests
  - gcov --object-directory .libs *.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
